[2023-02-23 22:36:49,156] ComponentOperator [INFO ] Monitoring namespace components [2023-02-23 22:57:42,626] ComponentOperator [INFO ] [r1-productcatalog|persistentvolumeclaim/r1-mongodb-pv-claim|adopt_persistentvolumeclaim|adopt_persistentvolumeclaim] Handler called: [2023-02-23 22:57:42,679] kopf.objects [ERROR ] [components/r1-mongodb-pv-claim] Handler 'adopt_persistentvolumeclaim' failed temporarily: Cannot find parent component r1-productcatalog [2023-02-23 22:57:42,693] ComponentOperator [INFO ] [r1-productcatalog|service/r1-productcatalog-sm|adopt_service|adopt_service] Handler called: [2023-02-23 22:57:42,724] kopf.objects [ERROR ] [components/r1-productcatalog-sm] Handler 'adopt_service' failed temporarily: Cannot find parent component r1-productcatalog [2023-02-23 22:57:42,731] ComponentOperator [INFO ] [r1-productcatalog|service/r1-mongodb|adopt_service|adopt_service] Handler called: [2023-02-23 22:57:42,765] kopf.objects [ERROR ] [components/r1-mongodb] Handler 'adopt_service' failed temporarily: Cannot find parent component r1-productcatalog [2023-02-23 22:57:42,767] ComponentOperator [INFO ] [r1-productcatalog|service/r1-prodcatapi|adopt_service|adopt_service] Handler called: [2023-02-23 22:57:42,807] kopf.objects [ERROR ] [components/r1-prodcatapi] Handler 'adopt_service' failed temporarily: Cannot find parent component r1-productcatalog [2023-02-23 22:57:42,820] ComponentOperator [INFO ] [r1-productcatalog|service/r1-partyroleapi|adopt_service|adopt_service] Handler called: [2023-02-23 22:57:42,911] ComponentOperator [INFO ] [r1-productcatalog|service/r1-partyroleapi|adopt_service|adopt_service] Adding component as parent of service: r1-productcatalog [2023-02-23 22:57:42,916] kopf.objects [WARNING ] [components/r1-mongodb-pv-claim] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'adopt_persistentvolumeclaim': {'started': '2023-02-23T22:57:42.626276', 'stopped': None, 'delayed': '2023-02-23T22:58:42.679389', 'purpose': 'create', 'retries': 1, 'success': False, 'failure': False, 'message': 'Cannot find parent component r1-productcatalog', 'subrefs': None}}}, None),) [2023-02-23 22:57:42,917] kopf.objects [WARNING ] [components/r1-productcatalog-sm] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'adopt_service': {'started': '2023-02-23T22:57:42.693033', 'stopped': None, 'delayed': '2023-02-23T22:58:42.724449', 'purpose': 'create', 'retries': 1, 'success': False, 'failure': False, 'message': 'Cannot find parent component r1-productcatalog', 'subrefs': None}}}, None),) [2023-02-23 22:57:42,922] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-mongodb|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 22:57:43,017] kopf.objects [ERROR ] [components/r1-mongodb] Handler 'adopt_deployment' failed temporarily: Conflict updating deployment. [2023-02-23 22:57:43,028] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-prodcatapi|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 22:57:43,115] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-prodcatapi|adopt_deployment|adopt_deployment] Adding component as parent of deployment: r1-productcatalog [2023-02-23 22:57:43,118] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-partyroleapi|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 22:57:43,211] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-partyroleapi|adopt_deployment|adopt_deployment] Adding component as parent of deployment: r1-productcatalog [2023-02-23 22:57:43,213] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-metricsapi|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 22:57:43,292] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-metricsapi|adopt_deployment|adopt_deployment] Adding component as parent of deployment: r1-productcatalog [2023-02-23 22:57:43,316] kopf.objects [WARNING ] [components/r1-mongodb] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'adopt_service': {'started': '2023-02-23T22:57:42.731497', 'stopped': None, 'delayed': '2023-02-23T22:58:42.765345', 'purpose': 'create', 'retries': 1, 'success': False, 'failure': False, 'message': 'Cannot find parent component r1-productcatalog', 'subrefs': None}}}, None),) [2023-02-23 22:57:43,319] kopf.objects [WARNING ] [components/r1-prodcatapi] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'adopt_service': {'started': '2023-02-23T22:57:42.767114', 'stopped': None, 'delayed': '2023-02-23T22:58:42.807885', 'purpose': 'create', 'retries': 1, 'success': False, 'failure': False, 'message': 'Cannot find parent component r1-productcatalog', 'subrefs': None}}}, None),) [2023-02-23 22:57:43,324] kopf.objects [WARNING ] [components/r1-mongodb] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'adopt_deployment': {'started': '2023-02-23T22:57:42.922066', 'stopped': None, 'delayed': '2023-02-23T22:58:43.017827', 'purpose': 'create', 'retries': 1, 'success': False, 'failure': False, 'message': 'Conflict updating deployment.', 'subrefs': None}}}, None),) [2023-02-23 22:57:51,393] kopf.objects [ERROR ] [components/r1-productcatalog-sm-x8l67] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 22:57:51,413] kopf.objects [WARNING ] [components/r1-productcatalog-sm-x8l67] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:57:51.339854', 'stopped': None, 'delayed': '2023-02-23T22:58:51.394356', 'purpose': 'update', 'retries': 1, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 22:58:04,626] kopf.objects [ERROR ] [components/r1-mongodb-hwsrx] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 22:58:04,647] kopf.objects [WARNING ] [components/r1-mongodb-hwsrx] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:04.578703', 'stopped': None, 'delayed': '2023-02-23T22:59:04.627342', 'purpose': 'update', 'retries': 1, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 22:58:05,211] kopf.objects [ERROR ] [components/r1-partyroleapi-m892k] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 22:58:05,224] kopf.objects [WARNING ] [components/r1-partyroleapi-m892k] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:05.177052', 'stopped': None, 'delayed': '2023-02-23T22:59:05.211626', 'purpose': 'update', 'retries': 1, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 22:58:09,587] kopf.objects [ERROR ] [components/r1-prodcatapi-p4t9b] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 22:58:09,607] kopf.objects [WARNING ] [components/r1-prodcatapi-p4t9b] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:09.538465', 'stopped': None, 'delayed': '2023-02-23T22:59:09.587473', 'purpose': 'update', 'retries': 1, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 22:58:42,777] kopf.objects [WARNING ] [components/r1-productcatalog-sm] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'dummy': '2023-02-23T22:58:42.725922'}, None),) [2023-02-23 22:58:42,785] kopf.objects [WARNING ] [components/r1-mongodb-pv-claim] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'dummy': '2023-02-23T22:58:42.691338'}, None),) [2023-02-23 22:58:42,817] kopf.objects [WARNING ] [components/r1-mongodb] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'dummy': '2023-02-23T22:58:42.766200'}, None),) [2023-02-23 22:58:42,830] kopf.objects [WARNING ] [components/r1-prodcatapi] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'dummy': '2023-02-23T22:58:42.808514'}, None),) [2023-02-23 22:58:42,880] ComponentOperator [INFO ] [r1-productcatalog|service/r1-productcatalog-sm|adopt_service|adopt_service] Handler called: [2023-02-23 22:58:42,960] ComponentOperator [INFO ] [r1-productcatalog|service/r1-productcatalog-sm|adopt_service|adopt_service] Adding component as parent of service: r1-productcatalog [2023-02-23 22:58:42,963] ComponentOperator [INFO ] [r1-productcatalog|persistentvolumeclaim/r1-mongodb-pv-claim|adopt_persistentvolumeclaim|adopt_persistentvolumeclaim] Handler called: [2023-02-23 22:58:43,047] ComponentOperator [INFO ] [r1-productcatalog|persistentvolumeclaim/r1-mongodb-pv-claim|adopt_persistentvolumeclaim|adopt_persistentvolumeclaim] Adding component as parent of persistentvolumeclaim: r1-productcatalog [2023-02-23 22:58:43,050] ComponentOperator [INFO ] [r1-productcatalog|service/r1-mongodb|adopt_service|adopt_service] Handler called: [2023-02-23 22:58:43,131] ComponentOperator [INFO ] [r1-productcatalog|service/r1-mongodb|adopt_service|adopt_service] Adding component as parent of service: r1-productcatalog [2023-02-23 22:58:43,134] ComponentOperator [INFO ] [r1-productcatalog|service/r1-prodcatapi|adopt_service|adopt_service] Handler called: [2023-02-23 22:58:43,222] ComponentOperator [INFO ] [r1-productcatalog|service/r1-prodcatapi|adopt_service|adopt_service] Adding component as parent of service: r1-productcatalog [2023-02-23 22:58:43,286] kopf.objects [WARNING ] [components/r1-mongodb] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'dummy': '2023-02-23T22:58:43.224708'}, None),) [2023-02-23 22:58:43,390] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-mongodb|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 22:58:43,469] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-mongodb|adopt_deployment|adopt_deployment] Adding component as parent of deployment: r1-productcatalog [2023-02-23 22:58:51,425] kopf.objects [WARNING ] [components/r1-productcatalog-sm-x8l67] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T22:58:51.397920'}}, None),) [2023-02-23 22:58:51,575] kopf.objects [ERROR ] [components/r1-productcatalog-sm-x8l67] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 22:58:51,591] kopf.objects [WARNING ] [components/r1-productcatalog-sm-x8l67] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:57:51.339854', 'stopped': None, 'delayed': '2023-02-23T22:59:51.575562', 'purpose': 'update', 'retries': 2, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 22:59:04,648] kopf.objects [WARNING ] [components/r1-mongodb-hwsrx] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T22:59:04.634760'}}, None),) [2023-02-23 22:59:04,792] kopf.objects [ERROR ] [components/r1-mongodb-hwsrx] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 22:59:04,803] kopf.objects [WARNING ] [components/r1-mongodb-hwsrx] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:04.578703', 'stopped': None, 'delayed': '2023-02-23T23:00:04.792766', 'purpose': 'update', 'retries': 2, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 22:59:05,227] kopf.objects [WARNING ] [components/r1-partyroleapi-m892k] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T22:59:05.212781'}}, None),) [2023-02-23 22:59:05,392] kopf.objects [ERROR ] [components/r1-partyroleapi-m892k] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 22:59:05,405] kopf.objects [WARNING ] [components/r1-partyroleapi-m892k] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:05.177052', 'stopped': None, 'delayed': '2023-02-23T23:00:05.392491', 'purpose': 'update', 'retries': 2, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 22:59:09,610] kopf.objects [WARNING ] [components/r1-prodcatapi-p4t9b] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T22:59:09.592313'}}, None),) [2023-02-23 22:59:09,760] kopf.objects [ERROR ] [components/r1-prodcatapi-p4t9b] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 22:59:09,773] kopf.objects [WARNING ] [components/r1-prodcatapi-p4t9b] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:09.538465', 'stopped': None, 'delayed': '2023-02-23T23:00:09.761082', 'purpose': 'update', 'retries': 2, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 22:59:51,642] kopf.objects [WARNING ] [components/r1-productcatalog-sm-x8l67] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T22:59:51.591260'}}, None),) [2023-02-23 22:59:51,789] kopf.objects [ERROR ] [components/r1-productcatalog-sm-x8l67] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 22:59:51,805] kopf.objects [WARNING ] [components/r1-productcatalog-sm-x8l67] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:57:51.339854', 'stopped': None, 'delayed': '2023-02-23T23:00:51.790042', 'purpose': 'update', 'retries': 3, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:00:04,812] kopf.objects [WARNING ] [components/r1-mongodb-hwsrx] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:00:04.794283'}}, None),) [2023-02-23 23:00:04,961] kopf.objects [ERROR ] [components/r1-mongodb-hwsrx] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:00:04,973] kopf.objects [WARNING ] [components/r1-mongodb-hwsrx] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:04.578703', 'stopped': None, 'delayed': '2023-02-23T23:01:04.961647', 'purpose': 'update', 'retries': 3, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:00:05,427] kopf.objects [WARNING ] [components/r1-partyroleapi-m892k] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:00:05.394002'}}, None),) [2023-02-23 23:00:05,565] kopf.objects [ERROR ] [components/r1-partyroleapi-m892k] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:00:05,584] kopf.objects [WARNING ] [components/r1-partyroleapi-m892k] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:05.177052', 'stopped': None, 'delayed': '2023-02-23T23:01:05.565904', 'purpose': 'update', 'retries': 3, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:00:09,783] kopf.objects [WARNING ] [components/r1-prodcatapi-p4t9b] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:00:09.764562'}}, None),) [2023-02-23 23:00:09,931] kopf.objects [ERROR ] [components/r1-prodcatapi-p4t9b] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:00:09,946] kopf.objects [WARNING ] [components/r1-prodcatapi-p4t9b] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:09.538465', 'stopped': None, 'delayed': '2023-02-23T23:01:09.931611', 'purpose': 'update', 'retries': 3, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:00:51,845] kopf.objects [WARNING ] [components/r1-productcatalog-sm-x8l67] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:00:51.802498'}}, None),) [2023-02-23 23:00:51,992] kopf.objects [ERROR ] [components/r1-productcatalog-sm-x8l67] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:00:52,004] kopf.objects [WARNING ] [components/r1-productcatalog-sm-x8l67] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:57:51.339854', 'stopped': None, 'delayed': '2023-02-23T23:01:51.992612', 'purpose': 'update', 'retries': 4, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:01:04,995] kopf.objects [WARNING ] [components/r1-mongodb-hwsrx] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:01:04.973015'}}, None),) [2023-02-23 23:01:05,130] kopf.objects [ERROR ] [components/r1-mongodb-hwsrx] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:01:05,142] kopf.objects [WARNING ] [components/r1-mongodb-hwsrx] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:04.578703', 'stopped': None, 'delayed': '2023-02-23T23:02:05.131332', 'purpose': 'update', 'retries': 4, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:01:05,583] kopf.objects [WARNING ] [components/r1-partyroleapi-m892k] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:01:05.566649'}}, None),) [2023-02-23 23:01:05,757] kopf.objects [ERROR ] [components/r1-partyroleapi-m892k] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:01:05,781] kopf.objects [WARNING ] [components/r1-partyroleapi-m892k] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:05.177052', 'stopped': None, 'delayed': '2023-02-23T23:02:05.757815', 'purpose': 'update', 'retries': 4, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:01:09,969] kopf.objects [WARNING ] [components/r1-prodcatapi-p4t9b] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:01:09.935361'}}, None),) [2023-02-23 23:01:10,123] kopf.objects [ERROR ] [components/r1-prodcatapi-p4t9b] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:01:10,159] kopf.objects [WARNING ] [components/r1-prodcatapi-p4t9b] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:09.538465', 'stopped': None, 'delayed': '2023-02-23T23:02:10.123541', 'purpose': 'update', 'retries': 4, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:01:52,042] kopf.objects [WARNING ] [components/r1-productcatalog-sm-x8l67] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:01:52.006628'}}, None),) [2023-02-23 23:01:52,197] kopf.objects [ERROR ] [components/r1-productcatalog-sm-x8l67] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:01:52,212] kopf.objects [WARNING ] [components/r1-productcatalog-sm-x8l67] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:57:51.339854', 'stopped': None, 'delayed': '2023-02-23T23:02:52.198089', 'purpose': 'update', 'retries': 5, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:02:05,165] kopf.objects [WARNING ] [components/r1-mongodb-hwsrx] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:02:05.144661'}}, None),) [2023-02-23 23:02:05,315] kopf.objects [ERROR ] [components/r1-mongodb-hwsrx] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:02:05,328] kopf.objects [WARNING ] [components/r1-mongodb-hwsrx] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:04.578703', 'stopped': None, 'delayed': '2023-02-23T23:03:05.316049', 'purpose': 'update', 'retries': 5, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:02:05,775] kopf.objects [WARNING ] [components/r1-partyroleapi-m892k] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:02:05.758950'}}, None),) [2023-02-23 23:02:05,907] kopf.objects [ERROR ] [components/r1-partyroleapi-m892k] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:02:05,927] kopf.objects [WARNING ] [components/r1-partyroleapi-m892k] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:05.177052', 'stopped': None, 'delayed': '2023-02-23T23:03:05.907706', 'purpose': 'update', 'retries': 5, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:02:10,154] kopf.objects [WARNING ] [components/r1-prodcatapi-p4t9b] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:02:10.126986'}}, None),) [2023-02-23 23:02:10,312] kopf.objects [ERROR ] [components/r1-prodcatapi-p4t9b] Handler 'implementation_status' failed with an exception. Will retry. Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 288, in execute_handler_once subrefs=subrefs, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/execution.py", line 382, in invoke_handler runtime=runtime, File "/usr/local/lib/python3.7/site-packages/kopf/_core/actions/invocation.py", line 139, in invoke await asyncio.shield(future) # slightly expensive: creates tasks File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "apiOperatorIstio/apiOperatorIstio.py", line 416, in implementation_status createAPIImplementationStatus(meta['ownerReferences'][0]['name'], body['endpoints'], namespace, 'implementation_status', componentName) File "apiOperatorIstio/apiOperatorIstio.py", line 459, in createAPIImplementationStatus logWrapper(logging.INFO, 'createAPIImplementationStatus', inHandler, 'endpointslice/' + api['metadata']['name'], componentName, "Can't find API resource", serviceName) UnboundLocalError: local variable 'api' referenced before assignment [2023-02-23 23:02:10,326] kopf.objects [WARNING ] [components/r1-prodcatapi-p4t9b] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'progress': {'implementation_status': {'started': '2023-02-23T22:58:09.538465', 'stopped': None, 'delayed': '2023-02-23T23:03:10.312730', 'purpose': 'update', 'retries': 5, 'success': False, 'failure': False, 'message': "local variable 'api' referenced before assignment", 'subrefs': None}}}}, None),) [2023-02-23 23:02:52,267] kopf.objects [WARNING ] [components/r1-productcatalog-sm-x8l67] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:02:52.210402'}}, None),) [2023-02-23 23:02:52,370] kopf.objects [ERROR ] [components/r1-productcatalog-sm-x8l67] Handler 'implementation_status' failed permanently: Handler 'implementation_status' has exceeded 5 retries. [2023-02-23 23:03:05,340] kopf.objects [WARNING ] [components/r1-mongodb-hwsrx] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:03:05.322384'}}, None),) [2023-02-23 23:03:05,443] kopf.objects [ERROR ] [components/r1-mongodb-hwsrx] Handler 'implementation_status' failed permanently: Handler 'implementation_status' has exceeded 5 retries. [2023-02-23 23:03:05,925] kopf.objects [WARNING ] [components/r1-partyroleapi-m892k] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:03:05.910419'}}, None),) [2023-02-23 23:03:06,028] kopf.objects [ERROR ] [components/r1-partyroleapi-m892k] Handler 'implementation_status' failed permanently: Handler 'implementation_status' has exceeded 5 retries. [2023-02-23 23:03:10,339] kopf.objects [WARNING ] [components/r1-prodcatapi-p4t9b] Patching failed with inconsistencies: (('remove', ('status',), {'kopf': {'dummy': '2023-02-23T23:03:10.316039'}}, None),) [2023-02-23 23:03:10,443] kopf.objects [ERROR ] [components/r1-prodcatapi-p4t9b] Handler 'implementation_status' failed permanently: Handler 'implementation_status' has exceeded 5 retries. [2023-02-23 23:51:20,818] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-prodcatapi|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 23:51:29,244] kopf.objects [ERROR ] [components/r1-prodcatapi] Handler 'adopt_deployment' failed temporarily: Conflict updating deployment. [2023-02-23 23:51:29,248] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-metricsapi|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 23:51:29,324] kopf.objects [ERROR ] [components/r1-metricsapi] Handler 'adopt_deployment' failed temporarily: Conflict updating deployment. [2023-02-23 23:51:29,327] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-partyroleapi|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 23:51:29,421] kopf.objects [ERROR ] [components/r1-partyroleapi] Handler 'adopt_deployment' failed temporarily: Conflict updating deployment. [2023-02-23 23:51:29,424] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-mongodb|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 23:51:29,496] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-mongodb|adopt_deployment|adopt_deployment] Adding component as parent of deployment: r1-productcatalog [2023-02-23 23:51:29,563] kopf.objects [WARNING ] [components/r1-partyroleapi] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'adopt_deployment': {'started': '2023-02-23T23:51:29.327372', 'stopped': None, 'delayed': '2023-02-23T23:52:29.421706', 'purpose': 'create', 'retries': 1, 'success': False, 'failure': False, 'message': 'Conflict updating deployment.', 'subrefs': None}}}, None),) [2023-02-23 23:51:29,565] kopf.objects [WARNING ] [components/r1-metricsapi] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'adopt_deployment': {'started': '2023-02-23T23:51:29.248621', 'stopped': None, 'delayed': '2023-02-23T23:52:29.324979', 'purpose': 'create', 'retries': 1, 'success': False, 'failure': False, 'message': 'Conflict updating deployment.', 'subrefs': None}}}, None),) [2023-02-23 23:51:32,377] kopf.objects [WARNING ] [components/r1-prodcatapi] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'adopt_deployment': {'started': '2023-02-23T23:51:20.817794', 'stopped': None, 'delayed': '2023-02-23T23:52:29.244602', 'purpose': 'create', 'retries': 1, 'success': False, 'failure': False, 'message': 'Conflict updating deployment.', 'subrefs': None}}}, None),) [2023-02-23 23:52:29,334] kopf.objects [WARNING ] [components/r1-prodcatapi] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'dummy': '2023-02-23T23:52:29.270046'}, None),) [2023-02-23 23:52:29,379] kopf.objects [WARNING ] [components/r1-metricsapi] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'dummy': '2023-02-23T23:52:29.325439'}, None),) [2023-02-23 23:52:29,450] kopf.objects [WARNING ] [components/r1-partyroleapi] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'dummy': '2023-02-23T23:52:29.422906'}, None),) [2023-02-23 23:52:29,471] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-prodcatapi|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 23:52:29,578] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-prodcatapi|adopt_deployment|adopt_deployment] Adding component as parent of deployment: r1-productcatalog [2023-02-23 23:52:29,581] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-partyroleapi|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 23:52:29,694] kopf.objects [ERROR ] [components/r1-partyroleapi] Handler 'adopt_deployment' failed temporarily: Conflict updating deployment. [2023-02-23 23:52:29,697] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-metricsapi|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 23:52:29,771] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-metricsapi|adopt_deployment|adopt_deployment] Adding component as parent of deployment: r1-productcatalog [2023-02-23 23:52:29,801] kopf.objects [WARNING ] [components/r1-partyroleapi] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'progress': {'adopt_deployment': {'started': '2023-02-23T23:51:29.327372', 'stopped': None, 'delayed': '2023-02-23T23:53:29.694800', 'purpose': 'create', 'retries': 2, 'success': False, 'failure': False, 'message': 'Conflict updating deployment.', 'subrefs': None}}}, None),) [2023-02-23 23:53:29,791] kopf.objects [WARNING ] [components/r1-partyroleapi] Patching failed with inconsistencies: (('remove', ('status', 'kopf'), {'dummy': '2023-02-23T23:53:29.731609'}, None),) [2023-02-23 23:53:29,942] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-partyroleapi|adopt_deployment|adopt_deployment] Handler called: [2023-02-23 23:53:30,077] ComponentOperator [INFO ] [r1-productcatalog|deployment/r1-partyroleapi|adopt_deployment|adopt_deployment] Adding component as parent of deployment: r1-productcatalog
